/**
 * src/types/index.ts
 * Global TypeScript type definitions for the Ayaan Cafe Website.
 *
 * This file defines interfaces for database models, API responses, and various
 * application-specific entities like menu items, orders, and reservations.
 */

// --- Database Models (derived from prisma/schema.prisma) ---
// Note: `createdAt` and `updatedAt` are common Prisma fields, added for completeness.

export interface User {
  id: number;
  name: string;
  email: string;
  // In a real application, this would likely include passwordHash, role, createdAt, updatedAt etc.
}

export interface Post {
  id: number;
  title: string;
  slug: string;
  content: string;
  authorId: number;
  author?: User; // Relation: The author of the post
  createdAt: Date; // Auto-generated by Prisma
  updatedAt: Date; // Auto-generated by Prisma
}

export interface Category {
  id: number;
  name: string;
  // posts?: Post[]; // Relation: Posts belonging to this category
  createdAt: Date;
  updatedAt: Date;
}

export interface Comment {
  id: number;
  content: string;
  postId: number;
  post?: Post; // Relation: The post this comment belongs to
  authorName: string; // Name of the commenter (could be a User relation too)
  createdAt: Date;
  updatedAt: Date;
}

// --- Menu System ---

/**
 * Represents an option for a menu item, e.g., 'Small', 'Large' for a coffee.
 */
export interface MenuItemOption {
  id: string; // Unique ID for the option, e.g., 'size-small', 'extra-cheese'
  name: string; // Display name, e.g., 'Small', 'Extra Cheese'
  price: number; // Additional price for this option (can be 0)
}

/**
 * Represents a group of options for a menu item, e.g., 'Sizes', 'Add-ons'.
 */
export interface MenuItemOptionGroup {
  id: string; // Unique ID for the option group, e.g., 'sizes', 'add-ons'
  name: string; // Display name, e.g., 'Select Size', 'Choose Toppings'
  options: MenuItemOption[];
  selectionType: 'single' | 'multiple'; // 'single' for radio buttons, 'multiple' for checkboxes
  minSelection?: number; // Minimum number of options to select from this group
  maxSelection?: number; // Maximum number of options to select from this group
}

/**
 * Represents a single item on the cafe's menu.
 */
export interface MenuItem {
  id: number;
  name: string;
  description: string;
  price: number;
  imageUrl?: string; // URL to the item's image
  categoryId: number;
  category?: MenuCategory; // Relation: The category this item belongs to
  isAvailable: boolean; // Whether the item is currently available for order
  allergens?: string[]; // List of common allergens, e.g., ['nuts', 'dairy']
  optionsGroups?: MenuItemOptionGroup[]; // Groups of customizable options for this item
  createdAt: Date;
  updatedAt: Date;
}

/**
 * Represents a category for menu items, e.g., 'Coffee', 'Pastries', 'Sandwiches'.
 */
export interface MenuCategory {
  id: number;
  name: string;
  description?: string;
  imageUrl?: string; // Optional image for the category
  // items?: MenuItem[]; // Relation: Menu items belonging to this category
  createdAt: Date;
  updatedAt: Date;
}

// --- Online Ordering System ---

/**
 * Represents an item in the user's shopping cart.
 */
export interface CartItem {
  menuItemId: number;
  name: string;
  price: number;
  quantity: number;
  selectedOptions?: {
    groupId: string;
    optionId: string;
    name: string;
    price: number;
  }[];
  imageUrl?: string;
  subtotal: number; // Calculated price for this cart item (price * quantity + options prices)
}

export type OrderType = 'pickup' | 'delivery';
export type OrderStatus = 'pending' | 'confirmed' | 'preparing' | 'ready' | 'completed' | 'cancelled' | 'refunded';
export type PaymentStatus = 'pending' | 'paid' | 'failed' | 'refunded';

/**
 * Details for a delivery order.
 */
export interface DeliveryInfo {
  address: string;
  city: string;
  zipCode: string;
  notes?: string; // Special delivery instructions
  contactPhone: string;
  contactName: string;
}

/**
 * Details for a pickup order.
 */
export interface PickupInfo {
  pickupTime: Date; // The scheduled time for pickup
  notes?: string; // Special pickup instructions
  contactPhone: string;
  contactName: string;
}

/**
 * Represents a single item within a confirmed order.
 */
export interface OrderItem {
  id: number;
  orderId: number;
  menuItemId: number;
  name: string;
  price: number;
  quantity: number;
  selectedOptions?: {
    groupId: string;
    optionId: string;
    name: string;
    price: number;
  }[];
  subtotal: number; // Total price for this specific order item
}

/**
 * Represents a complete online order.
 */
export interface Order {
  id: number;
  userId?: number; // Optional, for guest orders
  user?: User; // Relation: The user who placed the order
  status: OrderStatus;
  orderType: OrderType;
  totalAmount: number; // Sum of all order items and delivery fees
  orderItems: OrderItem[];
  deliveryInfo?: DeliveryInfo; // Present if orderType is 'delivery'
  pickupInfo?: PickupInfo; // Present if orderType is 'pickup'
  paymentStatus: PaymentStatus;
  createdAt: Date;
  updatedAt: Date;
}

// --- Online Table Reservation System ---

export type ReservationStatus = 'pending' | 'confirmed' | 'seated' | 'completed' | 'cancelled' | 'no-show';

/**
 * Represents a table reservation.
 */
export interface Reservation {
  id: number;
  userId?: number; // Optional, for guest reservations
  user?: User; // Relation: The user who made the reservation
  name: string;
  email: string;
  phone: string;
  date: Date; // The date of the reservation
  time: string; // The time of the reservation, e.g., "19:00"
  numberOfGuests: number;
  status: ReservationStatus;
  notes?: string; // Special requests or notes for the reservation
  createdAt: Date;
  updatedAt: Date;
}

// --- Contact & Location Page ---

/**
 * Defines the opening and closing times for a specific day.
 */
export interface BusinessHours {
  day: string; // e.g., 'Monday', 'Tuesday'
  open: string; // Opening time, e.g., '09:00'
  close: string; // Closing time, e.g., '22:00'
  isClosed?: boolean; // True if the business is closed on this day
}

/**
 * Information about a specific cafe location.
 */
export interface LocationInfo {
  name: string; // Name of the location, e.g., 'Downtown Branch'
  address: string;
  city: string;
  zipCode: string;
  phone: string;
  email: string;
  latitude?: number; // For map integration
  longitude?: number; // For map integration
  hours: BusinessHours[]; // Array of business hours for each day
}

// --- General API Responses & Utilities ---

/**
 * Standard structure for API responses.
 */
export interface ApiResponse<T> {
  success: boolean;
  data?: T;
  error?: string; // Error message if success is false
  message?: string; // General message
}

/**
 * Standard structure for paginated API responses.
 */
export interface PaginatedResponse<T> {
  data: T[];
  page: number;
  pageSize: number;
  totalItems: number;
  totalPages: number;
}
